using System.Text;
using Microsoft.CodeAnalysis;

namespace LitheEcs.SourceGenerator;

[Generator]
public sealed class QueryGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var worldType = context.Compilation.GetTypeByMetadataName("LitheEcs.World");
        if (worldType == null || worldType.DeclaringSyntaxReferences.Length == 0)
            return;

        context.AddSource("GeneratedQueries.g.cs", GenerateQueries(2, 8));
    }

    private static string GenerateQueries(int minimumArity, int maximumArity)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System;");
        source.AppendLine("using System.Runtime.CompilerServices;");
        source.AppendLine("namespace LitheEcs");
        source.AppendLine("{");

        for (int arity = minimumArity; arity <= maximumArity; arity++)
        {
            if (arity >= 5)
            {
                AppendDelegate(source, arity);
                AppendParallelRangeDelegate(source, arity);
                AppendActionInterface(source, arity);
            }
            AppendArchetypeQuery(source, arity);
            AppendParallelQuery(source, arity);
        }

        source.AppendLine("    public static partial class ParallelQueryExtensions");
        source.AppendLine("    {");
        for (int arity = minimumArity; arity <= maximumArity; arity++)
            AppendAsParallelQuery(source, arity);
        source.AppendLine("    }");

        source.AppendLine("    public sealed partial class World");
        source.AppendLine("    {");
        for (int arity = 5; arity <= maximumArity; arity++)
            AppendWorldFactory(source, arity);
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }

    private static void AppendParallelQuery(StringBuilder source, int arity)
    {
        var types = TypeParameters(arity);
        source.Append("    public readonly struct ParallelQuery<").Append(types).Append('>')
            .Append(Constraints(arity)).AppendLine();
        source.AppendLine("    {");
        source.Append("        private readonly Query<").Append(types).AppendLine("> _source;");
        source.AppendLine("        public int MinimumEntityCount { get; }");
        source.AppendLine("        public int BatchSize { get; }");
        source.Append("        internal ParallelQuery(Query<").Append(types)
            .AppendLine("> source, int minimumEntityCount, int batchSize)");
        source.AppendLine("        { if (minimumEntityCount < 1) throw new ArgumentOutOfRangeException(nameof(minimumEntityCount)); if (batchSize < 1) throw new ArgumentOutOfRangeException(nameof(batchSize)); _source = source; MinimumEntityCount = minimumEntityCount; BatchSize = batchSize; }");
        source.AppendLine("        public void Reserve(int maximumEntityCount) => _source.ReserveParallelRangesCore(maximumEntityCount, BatchSize);");
        source.Append("        public void Run(ParallelRangeAction<").Append(types)
            .AppendLine("> action) => _source.ParallelForRanges(action, MinimumEntityCount, BatchSize);");
        source.AppendLine("    }");
    }

    private static void AppendAsParallelQuery(StringBuilder source, int arity)
    {
        var types = TypeParameters(arity);
        source.Append("        public static ParallelQuery<").Append(types).Append("> AsParallelQuery<")
            .Append(types).Append(">(this Query<").Append(types)
            .Append("> query, int minimumEntityCount = 4096, int batchSize = 4096)")
            .Append(Constraints(arity)).Append(" => new ParallelQuery<").Append(types)
            .AppendLine(">(query, minimumEntityCount, batchSize);");
    }

    private static void AppendDelegate(StringBuilder source, int arity)
    {
        source.Append("    public delegate void QueryAction<").Append(TypeParameters(arity)).Append(">(in Entity entity");
        for (int i = 1; i <= arity; i++) source.Append(", ref T").Append(i).Append(" c").Append(i);
        source.Append(')').Append(Constraints(arity)).AppendLine(";");
    }

    private static void AppendParallelRangeDelegate(StringBuilder source, int arity)
    {
        source.Append("    public delegate void ParallelRangeAction<").Append(TypeParameters(arity)).Append(">(");
        for (var i = 1; i <= arity; i++)
            source.Append(i == 1 ? "" : ", ").Append("Span<T").Append(i).Append("> c").Append(i);
        source.Append(", EntityRange entities)").Append(Constraints(arity)).AppendLine(";");
    }

    private static void AppendActionInterface(StringBuilder source, int arity)
    {
        source.Append("    public interface IQueryAction<").Append(TypeParameters(arity)).Append('>').Append(Constraints(arity)).AppendLine();
        source.AppendLine("    {");
        source.Append("        void Execute(in Entity entity");
        for (int i = 1; i <= arity; i++) source.Append(", ref T").Append(i).Append(" c").Append(i);
        source.AppendLine(");");
        source.AppendLine("    }");
    }

    private static void AppendWorldFactory(StringBuilder source, int arity)
    {
        var types = TypeParameters(arity);
        source.Append("        [MethodImpl(MethodImplOptions.AggressiveInlining)] public Query<")
            .Append(types).Append("> Query<").Append(types).Append(">()")
            .Append(Constraints(arity)).Append(" { FlushStructuralBatch(); return new Query<").Append(types).AppendLine(">(this); }");
    }

    private static void AppendArchetypeQuery(StringBuilder source, int arity)
    {
        var types = TypeParameters(arity);
        source.Append("    public readonly struct Query<").Append(types).Append('>').Append(Constraints(arity)).AppendLine();
        source.AppendLine("    {");
        source.Append("        private static readonly int[] RequiredTypes = { ");
        for (var i = 1; i <= arity; i++)
            source.Append(i == 1 ? "" : ", ").Append("ComponentType<T").Append(i).Append(">.Id");
        source.AppendLine(" };");
        source.AppendLine("        private readonly World _world;");
        source.AppendLine("        private readonly ArchetypeQueryPlan _plan;");
        source.AppendLine("        private readonly bool _allowAligned;");
        source.Append("        public Query(World world) { world.FlushStructuralBatch(); world.ThrowIfDisposed(); _world = world; _plan = world.GetOrCreateBaseArchetypeQueryPlan(typeof(Query<")
            .Append(types).AppendLine(">), RequiredTypes); _allowAligned = true; }");
        source.AppendLine("        private Query(World world, ArchetypeQueryPlan plan) { _world = world; _plan = plan; _allowAligned = false; }");
        source.Append("        public Query<").Append(types).Append("> With<T>() where T : struct { var required = ComponentTypeIdList.Add(_plan.Required, ComponentType<T>.Id); return new Query<")
            .Append(types).AppendLine(">(_world, _world.CreateArchetypeQueryPlan(required, _plan.Excluded, _plan.Any)); }");
        source.Append("        public Query<").Append(types).Append("> Without<T>() where T : struct { var excluded = ComponentTypeIdList.Add(_plan.Excluded, ComponentType<T>.Id); return new Query<")
            .Append(types).AppendLine(">(_world, _world.CreateArchetypeQueryPlan(_plan.Required, excluded, _plan.Any)); }");
        source.Append("        public Query<").Append(types).Append("> Any<TAny1, TAny2>() where TAny1 : struct where TAny2 : struct { var any = ComponentTypeIdList.Add(_plan.Any, ComponentType<TAny1>.Id); any = ComponentTypeIdList.Add(any, ComponentType<TAny2>.Id); return new Query<")
            .Append(types).AppendLine(">(_world, _world.CreateArchetypeQueryPlan(_plan.Required, _plan.Excluded, any)); }");
        source.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool Matches(Entity entity) => _world.Matches(entity, _plan);");
        source.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)] public Enumerator GetEnumerator() { _world.FlushStructuralBatch(); _world.ThrowIfDisposed(); return new Enumerator(_world, _plan); }");
        source.AppendLine("        /// <summary>Builds this Query's current Archetype match cache without visiting entities.</summary>");
        source.Append("        public Query<").Append(types).AppendLine("> Warmup() { _world.FlushStructuralBatch(); _world.ThrowIfDisposed(); _plan.Ensure(); return this; }");

        AppendArchetypeForEach(source, arity, types, false);
        AppendArchetypeForEach(source, arity, types, true);
        if (arity <= 3) AppendArchetypeJobRangeLease(source, arity, types);
        AppendArchetypeParallelRangeReservation(source, arity, types);
        AppendArchetypeParallelRanges(source, arity, types);
        AppendArchetypeEnumerator(source, arity);
        AppendArchetypeAligned(source, arity, types);
        AppendArchetypeRefTuple(source, arity);
        if (arity == 2) AppendRefItem(source);
        source.AppendLine("    }");
    }

    private static void AppendArchetypeParallelRangeReservation(StringBuilder source, int arity, string types)
    {
        source.AppendLine("        internal void ReserveParallelRangesCore(int maximumEntityCount, int batchSize)");
        source.AppendLine("        { _world.FlushStructuralBatch(); _world.ThrowIfDisposed(); if (maximumEntityCount < 0) throw new ArgumentOutOfRangeException(nameof(maximumEntityCount)); if (batchSize < 1) throw new ArgumentOutOfRangeException(nameof(batchSize)); _plan.Ensure();");
        source.AppendLine("          var job = _plan.ParallelRangeJob as ParallelRangeJob; if (job == null) _plan.ParallelRangeJob = job = new ParallelRangeJob();");
        source.AppendLine("          job.EnsureItemCapacity(World.GetParallelRangeReservationCount(maximumEntityCount, _plan.Matches.Count, batchSize)); }");
    }

    private static void AppendArchetypeJobRangeLease(StringBuilder source, int arity, string types)
    {
        source.Append("        internal JobQueryRangeLease<").Append(types).AppendLine("> AcquireJobRanges()");
        source.Append("        { _world.FlushStructuralBatch(); _world.ThrowIfDisposed(); _plan.Ensure(); _world.EnterParallelQuery(); return new JobQueryRangeLease<")
            .Append(types).AppendLine(">(_world, _plan.Matches); }");
        source.AppendLine("        internal void GetJobRangeReservationCounts(int maximumEntityCount, int batchSize, out int rangeCount, out int workCount)");
        source.AppendLine("        { _world.FlushStructuralBatch(); _world.ThrowIfDisposed(); if (maximumEntityCount < 0) throw new ArgumentOutOfRangeException(nameof(maximumEntityCount)); if (batchSize < 1) throw new ArgumentOutOfRangeException(nameof(batchSize)); _plan.Ensure(); var matchingArchetypeCount = _plan.Matches.Count;");
        source.AppendLine("          rangeCount = World.GetParallelRangeReservationCount(maximumEntityCount, matchingArchetypeCount, ComponentPageManager.PageCapacity);");
        source.AppendLine("          var workItemsPerRange = (ComponentPageManager.PageCapacity - 1) / batchSize + 1;");
        source.AppendLine("          workCount = checked(rangeCount * workItemsPerRange); }");
    }

    private static void AppendArchetypeForEach(StringBuilder source, int arity, string types, bool structAction)
    {
        if (structAction)
            source.Append("        public void ForEach<TAction>(ref TAction action) where TAction : struct, IQueryAction<").Append(types).AppendLine(">");
        else
            source.Append("        public void ForEach(QueryAction<").Append(types).AppendLine("> action)");
        source.AppendLine("        {");
        if (!structAction) source.AppendLine("            if (action == null) throw new ArgumentNullException(nameof(action));");
        source.AppendLine("            _world.FlushStructuralBatch(); _world.ThrowIfDisposed(); _plan.Ensure(); var version = _world.StructuralVersion; var matches = _plan.Matches; var world = _world;");
        source.AppendLine("            for (var a = 0; a < matches.Count; a++) { var archetype = matches[a]; for (var c = 0; c < archetype.Chunks.Count; c++) { var chunk = archetype.Chunks[c]; var count = chunk.Count; if (count == 0) continue; world.ValidateQueryStructuralVersion(version);");
        for (var i = 1; i <= arity; i++)
            source.Append("                var d").Append(i).Append(" = archetype.GetColumn<T").Append(i).AppendLine(">(chunk);");
        source.AppendLine("                var entityIds = chunk.EntityIds; for (var n = 0; n < count; n++) { var entity = world.GetEntity(entityIds[n]);");
        source.Append(structAction ? "                    action.Execute(in entity" : "                    action(in entity");
        for (var i = 1; i <= arity; i++) source.Append(", ref d").Append(i).Append("[n]");
        source.AppendLine(");");
        source.AppendLine("                } } }");
        source.AppendLine("        }");
    }

    private static void AppendArchetypeParallelRanges(StringBuilder source, int arity, string types)
    {
        source.Append("        internal void ParallelForRanges(ParallelRangeAction<").Append(types).AppendLine("> action, int minimumEntityCount, int batchSize)");
        source.AppendLine("        { if (action == null) throw new ArgumentNullException(nameof(action)); _world.FlushStructuralBatch(); _world.ThrowIfDisposed(); _plan.Ensure(); var matches = _plan.Matches; var entityCount = 0; for (var i = 0; i < matches.Count; i++) entityCount += matches[i].EntityCount; _world.EnterParallelQuery(); try {");
        source.AppendLine("            if (entityCount < minimumEntityCount || Environment.ProcessorCount <= 1) { var queryOffset = 0; for (var a = 0; a < matches.Count; a++) { var archetype = matches[a]; for (var c = 0; c < archetype.Chunks.Count; c++) { var chunk = archetype.Chunks[c]; var count = chunk.Count; if (count == 0) continue;");
        source.Append("                action(");
        for (var i = 1; i <= arity; i++)
            source.Append(i == 1 ? "" : ", ").Append("archetype.GetColumn<T").Append(i).Append(">(chunk).AsSpan(0, count)");
        source.AppendLine(", new EntityRange(_world, chunk.EntityIds, 0, count, queryOffset)); queryOffset += count; } } return; }");
        source.AppendLine("            var job = _plan.ParallelRangeJob as ParallelRangeJob; if (job == null) _plan.ParallelRangeJob = job = new ParallelRangeJob(); job.World = _world; job.Action = action; job.Prepare(matches, batchSize); _world.ExecuteParallelQuery(job);");
        source.AppendLine("        } catch (AggregateException) { throw; } catch (Exception exception) { throw new AggregateException(exception); } finally { _world.ExitParallelQuery(); } }");

        source.AppendLine("        private sealed class ParallelRangeJob : ParallelQueryJob");
        source.AppendLine("        { internal World World = null!;");
        source.Append("            internal ParallelRangeAction<").Append(types).AppendLine("> Action = null!;");
        source.AppendLine("            protected override void Execute(in ParallelQueryWorkItem item) { var archetype = item.Archetype; var chunk = item.Chunk; var length = item.End - item.Start;");
        source.Append("                Action(");
        for (var i = 1; i <= arity; i++)
            source.Append(i == 1 ? "" : ", ").Append("archetype.GetColumn<T").Append(i).Append(">(chunk).AsSpan(item.Start, length)");
        source.AppendLine(", new EntityRange(World, chunk.EntityIds, item.Start, length, item.QueryOffset)); } }");
    }

    private static void AppendArchetypeEnumerator(StringBuilder source, int arity)
    {
        source.AppendLine("        public ref struct Enumerator");
        source.AppendLine("        { private readonly World _world; private readonly int _version; private readonly ArchetypeQueryPlan _plan; private int _a, _c, _row, _count;");
        for (var i = 1; i <= arity; i++) source.Append("          private T").Append(i).Append("[]? _d").Append(i).AppendLine(";");
        source.AppendLine("          private int[]? _entityIds;");
        source.AppendLine("          internal int CurrentEntityIndex => _entityIds![_row];");
        source.AppendLine("          internal Enumerator(World world, ArchetypeQueryPlan plan) { plan.Ensure(); _world = world; _version = world.StructuralVersion; _plan = plan; _a = 0; _c = 0; _row = -1; _count = 0; _entityIds = null;");
        for (var i = 1; i <= arity; i++) source.Append("            _d").Append(i).AppendLine(" = null;");
        source.AppendLine("          }");
        source.AppendLine("          public bool MoveNext() { if (++_row < _count) return true; var matches = _plan.Matches; while (_a < matches.Count) { var archetype = matches[_a]; if (_c >= archetype.Chunks.Count) { _a++; _c = 0; continue; } var chunk = archetype.Chunks[_c++]; _count = chunk.Count; if (_count == 0) continue; _world.ValidateQueryStructuralVersion(_version); _entityIds = chunk.EntityIds;");
        for (var i = 1; i <= arity; i++)
            source.Append("              _d").Append(i).Append(" = archetype.GetColumn<T").Append(i).AppendLine(">(chunk);");
        source.AppendLine("              _row = 0; return true; } return false; }");
        source.Append("          public RefTuple Current { get => new RefTuple(");
        for (var i = 1; i <= arity; i++) source.Append(i == 1 ? "" : ", ").Append("_d").Append(i).Append("!, _row");
        source.AppendLine("); } }");
    }

    private static void AppendArchetypeRefTuple(StringBuilder source, int arity)
    {
        source.AppendLine("        public readonly ref struct RefTuple {");
        for (var i = 1; i <= arity; i++) source.Append("          private readonly T").Append(i).Append("[] _d").Append(i).Append("; private readonly int _i").Append(i).AppendLine(";");
        source.Append("          internal RefTuple(");
        for (var i = 1; i <= arity; i++) source.Append(i == 1 ? "" : ", ").Append("T").Append(i).Append("[] d").Append(i).Append(", int i").Append(i);
        source.AppendLine(") {");
        for (var i = 1; i <= arity; i++) source.Append("            _d").Append(i).Append(" = d").Append(i).Append("; _i").Append(i).Append(" = i").Append(i).AppendLine(";");
        source.AppendLine("          }");
        source.Append("          public void Deconstruct(");
        for (var i = 1; i <= arity; i++) source.Append(i == 1 ? "" : ", ").Append("out Query<T1, T2>.RefItem<T").Append(i).Append("> c").Append(i);
        source.AppendLine(") {");
        for (var i = 1; i <= arity; i++) source.Append("            c").Append(i).Append(" = new Query<T1, T2>.RefItem<T").Append(i).Append(">(_d").Append(i).Append(", _i").Append(i).AppendLine(");");
        source.AppendLine("          } }");
    }

    private static void AppendArchetypeAligned(StringBuilder source, int arity, string types)
    {
        source.AppendLine("        public bool TryGetAlignedChunk(out AlignedChunk chunk) { if (!_allowAligned) { chunk = default; return false; } _plan.Ensure(); Archetype? found = null; ArchetypeChunk? foundChunk = null; var matches = _plan.Matches; for (var a = 0; a < matches.Count; a++) { var candidate = matches[a]; for (var c = 0; c < candidate.Chunks.Count; c++) { var candidateChunk = candidate.Chunks[c]; if (candidateChunk.Count == 0) continue; if (foundChunk != null) { chunk = default; return false; } found = candidate; foundChunk = candidateChunk; } } if (foundChunk == null) { chunk = default; return true; }");
        source.Append("          chunk = new AlignedChunk(");
        for (var i = 1; i <= arity; i++) source.Append(i == 1 ? "" : ", ").Append("found!.GetColumn<T").Append(i).Append(">(foundChunk)");
        source.AppendLine(", foundChunk.Count); return true; }");
        source.AppendLine("        public readonly ref struct AlignedChunk {");
        for (var i = 1; i <= arity; i++) source.Append("          public readonly Span<T").Append(i).Append("> Component").Append(i).Append("; internal readonly T").Append(i).Append("[] Array").Append(i).AppendLine(";");
        source.AppendLine("          private readonly int _length;");
        source.Append("          internal AlignedChunk(");
        for (var i = 1; i <= arity; i++) source.Append(i == 1 ? "" : ", ").Append("T").Append(i).Append("[] c").Append(i);
        source.AppendLine(", int length) {");
        for (var i = 1; i <= arity; i++) source.Append(" Array").Append(i).Append(" = c").Append(i).Append("; Component").Append(i).Append(" = c").Append(i).Append(".AsSpan(0, length);");
        source.AppendLine(" _length = length; } public int Length => _length; }");
    }

    private static void AppendPlannedQuery(StringBuilder source, int arity)
    {
        var types = TypeParameters(arity);
        source.Append("    public readonly struct Query<").Append(types).Append('>').Append(Constraints(arity)).AppendLine();
        source.AppendLine("    {");
        source.AppendLine("        private readonly World _world;");
        source.AppendLine("        private readonly Plan _plan;");
        source.AppendLine("        private readonly ComponentMask _allMask, _excludedMask, _anyMask;");
        source.Append("        public Query(World world) { world.ThrowIfDisposed(); _world = world; _plan = world.")
            .Append(arity <= 4 ? "GetOrCreateQueryPlan<" : "GetOrCreateGeneratedQueryPlan<")
            .Append(types).Append(">(); _allMask = default;");
        for (var i = 1; i <= arity; i++) source.Append(" _allMask.Set(ComponentType<T").Append(i).Append(">.Id);");
        source.AppendLine(" _excludedMask = default; _anyMask = default; }");
        source.Append("        private Query(World world, Plan plan, ComponentMask allMask, ComponentMask excludedMask, ComponentMask anyMask)")
            .AppendLine(" { _world = world; _plan = plan; _allMask = allMask; _excludedMask = excludedMask; _anyMask = anyMask; }");
        source.Append("        public Query<").Append(types).Append("> With<T>() where T : struct { var mask = _allMask; mask.Set(ComponentType<T>.Id); return new Query<")
            .Append(types).AppendLine(">(_world, _plan, mask, _excludedMask, _anyMask); }");
        source.Append("        public Query<").Append(types).Append("> Without<T>() where T : struct { var mask = _excludedMask; mask.Set(ComponentType<T>.Id); return new Query<")
            .Append(types).AppendLine(">(_world, _plan, _allMask, mask, _anyMask); }");
        source.Append("        public Query<").Append(types).Append("> Any<TAny1, TAny2>() where TAny1 : struct where TAny2 : struct { var mask = _anyMask; mask.Set(ComponentType<TAny1>.Id); mask.Set(ComponentType<TAny2>.Id); return new Query<")
            .Append(types).AppendLine(">(_world, _plan, _allMask, _excludedMask, mask); }");
        source.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool Matches(Entity entity) => _world.Matches(entity, _allMask, _excludedMask, _anyMask);");
        source.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)] public Enumerator GetEnumerator() => new Enumerator(_plan, _allMask, _excludedMask, _anyMask);");

        AppendPlannedForEach(source, arity, types, false);
        AppendPlannedForEach(source, arity, types, true);

        source.AppendLine("        public bool TryGetAlignedChunk(out AlignedChunk chunk)");
        source.AppendLine("        { _plan.Ensure(); if (!_excludedMask.IsEmpty || !_anyMask.IsEmpty || !_allMask.SameAs(_plan.ProjectedMask) || !_plan.IsAligned) { chunk = default; return false; }");
        source.AppendLine("          if (_plan.Count == 0) { chunk = default; return true; }");
        source.Append("          chunk = new AlignedChunk(");
        for (var i = 1; i <= arity; i++) source.Append(i == 1 ? "" : ", ").Append("_plan.S").Append(i).Append("!.DenseArray.AsSpan(0, _plan.Count)");
        source.AppendLine("); return true; }");

        source.AppendLine("        public ref struct Enumerator");
        source.AppendLine("        {");
        source.AppendLine("            private readonly World _world; private readonly int _structuralVersion; private readonly Plan _plan;");
        source.AppendLine("            private readonly ComponentMask _allMask, _excludedMask, _anyMask; private readonly bool _filtered, _aligned; private int _index;");
        for (var i = 1; i <= arity; i++) source.Append("            private readonly T").Append(i).Append("[] _d").Append(i).Append("; private int _i").Append(i).AppendLine(";");
        source.AppendLine("            internal int CurrentEntityIndex => _plan.Entities[_index];");
        source.AppendLine("            internal Enumerator(Plan plan, ComponentMask allMask, ComponentMask excludedMask, ComponentMask anyMask)");
        source.AppendLine("            { plan.Ensure(); _plan = plan; _world = plan.World; _structuralVersion = _world.StructuralVersion; _allMask = allMask; _excludedMask = excludedMask; _anyMask = anyMask; _filtered = !excludedMask.IsEmpty || !anyMask.IsEmpty || !allMask.SameAs(plan.ProjectedMask); _aligned = plan.IsAligned;");
        for (var i = 1; i <= arity; i++) source.Append("              _d").Append(i).Append(" = plan.S").Append(i).Append("?.DenseArray ?? Array.Empty<T").Append(i).AppendLine(">();");
        source.Append("              _index = -1;");
        for (var i = 1; i <= arity; i++) source.Append(" _i").Append(i).Append(" = -1;");
        source.AppendLine(" }");
        source.AppendLine("            [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool MoveNext()");
        source.AppendLine("            { _world.ValidateQueryStructuralVersion(_structuralVersion); while (++_index < _plan.Count) { if (_filtered) { var mask = _world.GetMask(_plan.Entities[_index]); if (!mask.ContainsAll(_allMask) || !mask.ContainsNone(_excludedMask) || (!_anyMask.IsEmpty && !mask.Intersects(_anyMask))) continue; }");
        source.AppendLine("                if (_aligned) {");
        for (var i = 1; i <= arity; i++) source.Append("                    _i").Append(i).AppendLine(" = _index;");
        source.AppendLine("                } else { var indices = _plan.Indices[_index];");
        for (var i = 1; i <= arity; i++) source.Append("                    _i").Append(i).Append(" = indices.I").Append(i).AppendLine(";");
        source.AppendLine("                } return true; } return false; }");
        source.Append("            public RefTuple Current { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => new RefTuple(");
        for (var i = 1; i <= arity; i++) source.Append(i == 1 ? "" : ", ").Append("_d").Append(i).Append(", _i").Append(i);
        source.AppendLine("); }");
        source.AppendLine("        }");

        AppendPlan(source, arity);

        source.AppendLine("        public readonly ref struct RefTuple");
        source.AppendLine("        {");
        for (var i = 1; i <= arity; i++) source.Append("            private readonly T").Append(i).Append("[] _d").Append(i).Append("; private readonly int _i").Append(i).AppendLine(";");
        source.Append("            internal RefTuple(");
        for (var i = 1; i <= arity; i++) source.Append(i == 1 ? "" : ", ").Append("T").Append(i).Append("[] d").Append(i).Append(", int i").Append(i);
        source.AppendLine(") {");
        for (var i = 1; i <= arity; i++) source.Append("                _d").Append(i).Append(" = d").Append(i).Append("; _i").Append(i).Append(" = i").Append(i).AppendLine(";");
        source.AppendLine("            }");
        source.Append("            [MethodImpl(MethodImplOptions.AggressiveInlining)] public void Deconstruct(");
        for (var i = 1; i <= arity; i++) source.Append(i == 1 ? "" : ", ").Append("out Query<T1, T2>.RefItem<T").Append(i).Append("> c").Append(i);
        source.AppendLine(") {");
        for (var i = 1; i <= arity; i++) source.Append("                c").Append(i).Append(" = new Query<T1, T2>.RefItem<T").Append(i).Append(">(_d").Append(i).Append(", _i").Append(i).AppendLine(");");
        source.AppendLine("            }");
        source.AppendLine("        }");


        source.AppendLine("        public readonly ref struct AlignedChunk");
        source.AppendLine("        {");
        for (var i = 1; i <= arity; i++) source.Append("            public readonly Span<T").Append(i).Append("> Component").Append(i).AppendLine(";");
        source.Append("            internal AlignedChunk(");
        for (var i = 1; i <= arity; i++) source.Append(i == 1 ? "" : ", ").Append("Span<T").Append(i).Append("> component").Append(i);
        source.AppendLine(") {");
        for (var i = 1; i <= arity; i++) source.Append("                Component").Append(i).Append(" = component").Append(i).AppendLine(";");
        source.AppendLine("            }");
        source.AppendLine("            public int Length => Component1.Length;");
        source.AppendLine("        }");
        if (arity == 2) AppendRefItem(source);
        source.AppendLine("    }");
    }

    private static void AppendRefItem(StringBuilder source)
    {
        source.AppendLine("        public readonly ref struct RefItem<T> where T : struct");
        source.AppendLine("        {");
        source.AppendLine("            private readonly T[] _dense; private readonly int _index;");
        source.AppendLine("            internal RefItem(T[] dense, int denseIndex) { _dense = dense; _index = denseIndex; }");
        source.AppendLine("            public ref T Value { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => ref _dense[_index]; }");
        source.AppendLine("            public static implicit operator T(RefItem<T> item) => item._dense[item._index];");
        source.AppendLine("        }");
    }

    private static void AppendPlannedForEach(StringBuilder source, int arity, string types, bool structAction)
    {
        if (structAction)
            source.Append("        public void ForEach<TAction>(ref TAction action) where TAction : struct, IQueryAction<").Append(types).AppendLine(">");
        else
            source.Append("        public void ForEach(QueryAction<").Append(types).AppendLine("> action)");
        source.AppendLine("        {");
        if (!structAction) source.AppendLine("            if (action == null) throw new ArgumentNullException(nameof(action));");
        source.AppendLine("            _plan.Ensure(); var plan = _plan; var filtered = !_excludedMask.IsEmpty || !_anyMask.IsEmpty || !_allMask.SameAs(plan.ProjectedMask);");
        source.AppendLine("            if (plan.Count == 0) return;");
        for (var i = 1; i <= arity; i++) source.Append("            var d").Append(i).Append(" = plan.S").Append(i).AppendLine("!.DenseArray;");
        source.AppendLine("            if (plan.IsAligned && !filtered) { for (var n = 0; n < plan.Count; n++) { var entity = _world.GetEntity(plan.Entities[n]);");
        source.Append(structAction ? "                action.Execute(in entity" : "                action(in entity");
        for (var i = 1; i <= arity; i++) source.Append(", ref d").Append(i).Append("[n]");
        source.AppendLine("); } return; }");
        source.AppendLine("            for (var n = 0; n < plan.Count; n++) { var entityIndex = plan.Entities[n]; if (filtered) { var mask = _world.GetMask(entityIndex); if (!mask.ContainsAll(_allMask) || !mask.ContainsNone(_excludedMask) || (!_anyMask.IsEmpty && !mask.Intersects(_anyMask))) continue; } var entity = _world.GetEntity(entityIndex); var indices = plan.Indices[n];");
        source.Append(structAction ? "                action.Execute(in entity" : "                action(in entity");
        for (var i = 1; i <= arity; i++) source.Append(", ref d").Append(i).Append("[indices.I").Append(i).Append("]");
        source.AppendLine("); }");
        source.AppendLine("        }");
    }

    private static void AppendPlan(StringBuilder source, int arity)
    {
        source.AppendLine("        internal sealed class Plan : IQueryPlan, IIncrementalQueryPlan");
        source.AppendLine("        {");
        source.AppendLine("            internal readonly World World; internal readonly ComponentMask ProjectedMask;");
        for (var i = 1; i <= arity; i++) source.Append("            internal ComponentStorage<T").Append(i).Append(">? S").Append(i).AppendLine(";");
        source.AppendLine("            internal int[] Entities = Array.Empty<int>();");
        source.AppendLine("            internal IndexRow[] Indices = Array.Empty<IndexRow>();");
        source.AppendLine("            internal int Count; internal bool IsAligned; private bool _dirty = true;");
        source.AppendLine("            internal Plan(World world) { World = world; ProjectedMask = CreateMask(); world.RegisterQueryPlan(this); world.RegisterIncrementalQueryPlan(this, ProjectedMask); }");
        source.AppendLine("            internal void Ensure() { World.ThrowIfDisposed(); if (!_dirty) return; _dirty = false; Count = 0; IsAligned = true;");
        for (var i = 1; i <= arity; i++) source.Append("                S").Append(i).Append(" = (ComponentStorage<T").Append(i).Append(">)World.GetStorage<T").Append(i).AppendLine(">();");
        source.Append("                if (");
        for (var i = 1; i <= arity; i++) source.Append(i == 1 ? "" : " || ").Append("S").Append(i).Append(" == null");
        source.AppendLine(") return; var driver = World.GetSmallestStorage(ProjectedMask); if (driver == null) return; EnsureCapacity(driver.Count); var entities = driver.DenseToEntityArray;");
        for (var i = 1; i <= arity; i++) source.Append("                IsAligned &= S").Append(i).AppendLine("!.Count == driver.Count;");
        source.AppendLine("                for (var n = 0; n < driver.Count; n++) { var entity = entities[n];");
        for (var i = 1; i <= arity; i++) source.Append("                    IsAligned &= S").Append(i).AppendLine("!.DenseToEntityArray[n] == entity;");
        for (var i = 1; i <= arity; i++) source.Append("                    var i").Append(i).Append(" = ReferenceEquals(driver, S").Append(i).Append(") ? n : S").Append(i).AppendLine("!.GetDenseIndex(entity);");
        source.Append("                    if (");
        for (var i = 1; i <= arity; i++) source.Append(i == 1 ? "" : " || ").Append("i").Append(i).Append(" < 0");
        source.AppendLine(") continue; Entities[Count] = entity;");
        source.Append("                    Indices[Count] = new IndexRow { ");
        for (var i = 1; i <= arity; i++) source.Append(i == 1 ? "" : ", ").Append("I").Append(i).Append(" = i").Append(i);
        source.AppendLine(" }; ");
        source.AppendLine("                    Count++; } }");
        source.AppendLine("            private static ComponentMask CreateMask() { var mask = default(ComponentMask);");
        for (var i = 1; i <= arity; i++) source.Append("                mask.Set(ComponentType<T").Append(i).AppendLine(">.Id);");
        source.AppendLine("                return mask; }");
        source.AppendLine("            private void EnsureCapacity(int count) { if (Entities.Length >= count) return; Entities = new int[count]; Indices = new IndexRow[count]; }");
        source.AppendLine("            void IIncrementalQueryPlan.OnFilterComponentChanged(int entityIndex) => _dirty = true;");
        source.AppendLine("            internal struct IndexRow {");
        for (var i = 1; i <= arity; i++) source.Append("                internal int I").Append(i).AppendLine(";");
        source.AppendLine("            }");
        source.AppendLine("            public void Clear() {");
        for (var i = 1; i <= arity; i++) source.Append("                S").Append(i).AppendLine(" = null;");
        source.AppendLine("                Entities = Array.Empty<int>();");
        source.AppendLine("                Indices = Array.Empty<IndexRow>(); Count = 0; IsAligned = false; _dirty = true; }");
        source.AppendLine("        }");
    }

    private static string TypeParameters(int arity)
    {
        var result = new StringBuilder();
        for (int i = 1; i <= arity; i++) result.Append(i == 1 ? "" : ", ").Append('T').Append(i);
        return result.ToString();
    }

    private static string Constraints(int arity)
    {
        var result = new StringBuilder();
        for (int i = 1; i <= arity; i++) result.Append(" where T").Append(i).Append(" : struct");
        return result.ToString();
    }

}
